"""src/spflow パッケージの公開 API をまとめるモジュール。"""

# 上位パッケージから `spflow.*` として参照する利用者向け導線を固定するため、
# サブパッケージ内部の実装詳細ではなく公開契約として残す型と関数だけを再公開する。
from .beamforming import (
    BandwiseArrayDesign,
    CBFBeamformer,
    CBFOverlapSaveBeamformer,
    CovarianceEstimator,
    MVDRFilter,
    MVDROverlapSaveBeamformer,
    MVDRWeightCallback,
    MVDRWeightDesigner,
    apply_beamformer,
    apply_beamformer_bands,
    apply_beamformer_filter_fft,
    apply_channel_window_to_steering,
    beam_response_rms_db,
    design_cbf_overlap_save_filters,
    design_cbf_weights,
    design_cbf_weights_with_channel_window,
    design_mvdr_overlap_save_filters,
    design_mvdr_weights,
    design_mvdr_weights_with_channel_window,
    estimate_covariance,
    forgetting_factor_from_integration_time,
    integration_blocks_from_integration_time,
    integrate_band_covariances,
    make_directions,
    recommended_integration_time_for_independent_samples,
)
from .buffer import FrameBuffer
from .callback import DoubleBufferCallback
# フィルタバンク群は解析・合成器の組み合わせが多いため、利用者がトップレベル import だけで
# 実験コードを組めるように代表的な構成要素を一箇所に集約する。
from .filterbank import (
    CausalAnalyticFrontend,
    CausalAnalyticFrontendStreamer,
    CausalAnalyticResult,
    DFT_FilterBank,
    DFTModulatedFilterDesigner,
    FiniteLengthPRChecker,
    FormalBandPacket,
    FormalComplexPRHalfbandStage,
    FormalNonuniformAnalysisResult,
    FormalNonuniformTreeFilterBank,
    FormalNonuniformTreeStreamingAnalyzer,
    FormalNonuniformTreeStreamingSynthesizer,
    FormalPacketBlock,
    FullDFTFilterBank,
    NonuniformAnalysisResult,
    NonuniformBandPacket,
    NonuniformBandSpec,
    NonuniformPacketBlock,
    NonuniformTreeFilterBank,
    NonuniformTreeStreamingAnalyzer,
    NonuniformTreeStreamingSynthesizer,
    PRChecker,
    PRDFTAnalysisBank,
    PRDFTFilterBank,
    PRDFTSynthesisBank,
    PolyphaseDFTFilterBank,
    PolyphaseDecomposition,
    PolyphasePRDFTAnalysisBank,
    PolyphasePRDFTSynthesisBank,
    PolyphasePRPairDesigner,
    PrototypeAnalysisDFTFilterBank,
    PrototypeFilter,
    PrototypePairDesigner,
    PrototypeSynthesisDFTFilterBank,
    design_hilbert_fir,
)
from .flow import Flow
from .frequency import OverlapSaveBuffer, ValidRegionExtractor, make_filter_fft
from .option import Option
from .scheduler import StepScheduler

# `__all__` はワイルドカード import の制御だけでなく、公開 API の棚卸しとしても使う。
# ここに含めない識別子は将来的に互換性なく変更し得る内部実装として扱う。
__all__ = [
    'Option',
    'Flow',
    'FrameBuffer',
    'OverlapSaveBuffer',
    'ValidRegionExtractor',
    'make_filter_fft',
    'StepScheduler',
    'DoubleBufferCallback',
    'design_hilbert_fir',
    'CausalAnalyticResult',
    'CausalAnalyticFrontend',
    'CausalAnalyticFrontendStreamer',
    'FormalBandPacket',
    'FormalComplexPRHalfbandStage',
    'FormalNonuniformAnalysisResult',
    'FormalNonuniformTreeFilterBank',
    'FormalPacketBlock',
    'FormalNonuniformTreeStreamingAnalyzer',
    'FormalNonuniformTreeStreamingSynthesizer',
    'NonuniformBandSpec',
    'NonuniformBandPacket',
    'NonuniformAnalysisResult',
    'NonuniformTreeFilterBank',
    'NonuniformPacketBlock',
    'NonuniformTreeStreamingAnalyzer',
    'NonuniformTreeStreamingSynthesizer',
    'PRDFTFilterBank',
    'FullDFTFilterBank',
    'PolyphaseDFTFilterBank',
    'PrototypeFilter',
    'PolyphaseDecomposition',
    'PrototypeAnalysisDFTFilterBank',
    'PrototypeSynthesisDFTFilterBank',
    'DFTModulatedFilterDesigner',
    'PRDFTAnalysisBank',
    'PRDFTSynthesisBank',
    'FiniteLengthPRChecker',
    'PrototypePairDesigner',
    'PolyphasePRDFTAnalysisBank',
    'PolyphasePRDFTSynthesisBank',
    'PolyphasePRPairDesigner',
    'PRChecker',
    'DFT_FilterBank',
    'BandwiseArrayDesign',
    'apply_channel_window_to_steering',
    'design_cbf_weights',
    'design_cbf_weights_with_channel_window',
    'design_cbf_overlap_save_filters',
    'CBFBeamformer',
    'CBFOverlapSaveBeamformer',
    'estimate_covariance',
    'integration_blocks_from_integration_time',
    'recommended_integration_time_for_independent_samples',
    'integrate_band_covariances',
    'forgetting_factor_from_integration_time',
    'CovarianceEstimator',
    'make_directions',
    'design_mvdr_weights',
    'design_mvdr_weights_with_channel_window',
    'design_mvdr_overlap_save_filters',
    'MVDRWeightDesigner',
    'MVDRWeightCallback',
    'beam_response_rms_db',
    'apply_beamformer',
    'apply_beamformer_bands',
    'apply_beamformer_filter_fft',
    'MVDRFilter',
    'MVDROverlapSaveBeamformer',
]
